import { Challenge, ChallengeParticipant, DailyCheckin } from '@types';
import { DEFAULT_USER } from '@constants';

const now = new Date();
const tomorrow = new Date(now.getTime() + 24 * 60 * 60 * 1000);
const nextWeek = new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000);
const twoWeeks = new Date(now.getTime() + 14 * 24 * 60 * 60 * 1000);

export const mockChallenges: Challenge[] = [
  {
    id: 'challenge-1',
    name: 'Cash Club',
    description: 'Walk 10k steps per day for 5 days to join the winner\'s cash club. The prize pool grows with each participant!',
    createdBy: 'user-steppa',
    creatorName: 'Steppa',
    creatorAvatar: '🦘',
    dailyTarget: 10000,
    durationDays: 5,
    entryFee: 20,
    prizePool: 920,
    participantCount: 46,
    joinedCount: 46,
    startDate: tomorrow.toISOString(),
    endDate: new Date(tomorrow.getTime() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'upcoming',
    rules: [
      'Complete 10,000 steps daily',
      'Must complete all 5 days to qualify',
      'Prize pool splits equally among completers',
      'Steps tracked via phone sensors',
    ],
    createdAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'challenge-2',
    name: 'High Rollers',
    description: 'Elite challenge for serious step collectors. Premium prize pool. 10k daily steps, 5 day commitment.',
    createdBy: 'user-john',
    creatorName: '@john',
    creatorAvatar: '🎩',
    dailyTarget: 10000,
    durationDays: 5,
    entryFee: 100,
    prizePool: 200,
    participantCount: 2,
    joinedCount: 2,
    startDate: tomorrow.toISOString(),
    endDate: new Date(tomorrow.getTime() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'upcoming',
    rules: [
      'Complete 10,000 steps daily',
      'Must complete all 5 days to qualify',
      'Top performer gets 50% of pool',
      'Steps tracked via phone sensors',
    ],
    createdAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'challenge-3',
    name: 'Daily Stride',
    description: 'Casual 7-day challenge. Perfect for beginners. Only 5k steps per day to stay in the game.',
    createdBy: 'user-wellness',
    creatorName: 'Wellness Club',
    creatorAvatar: '🏃',
    dailyTarget: 5000,
    durationDays: 7,
    entryFee: 10,
    prizePool: 450,
    participantCount: 45,
    joinedCount: 45,
    startDate: nextWeek.toISOString(),
    endDate: new Date(nextWeek.getTime() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'upcoming',
    rules: [
      'Complete 5,000 steps daily',
      'Must complete 6 out of 7 days',
      'Equal split among qualifiers',
    ],
    createdAt: new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'challenge-4',
    name: 'Marathon Month',
    description: 'Epic 30-day endurance challenge. Ultra-competitive. Serious runners only.',
    createdBy: 'user-ultra',
    creatorName: 'Ultra Runner',
    creatorAvatar: '🏅',
    dailyTarget: 15000,
    durationDays: 30,
    entryFee: 50,
    prizePool: 1500,
    participantCount: 28,
    joinedCount: 28,
    startDate: twoWeeks.toISOString(),
    endDate: new Date(twoWeeks.getTime() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'upcoming',
    rules: [
      'Complete 15,000 steps daily',
      'Must complete all 30 days',
      'Leaderboard ranking determines distribution',
      'Top 10 share 80% of pool',
    ],
    createdAt: new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'challenge-5',
    name: 'Quick Win',
    description: 'Fast 3-day challenge starting today. Low entry fee, quick results.',
    createdBy: 'user-speed',
    creatorName: 'Speed Racer',
    creatorAvatar: '⚡',
    dailyTarget: 8000,
    durationDays: 3,
    entryFee: 15,
    prizePool: 180,
    participantCount: 12,
    joinedCount: 12,
    startDate: now.toISOString(),
    endDate: new Date(now.getTime() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'live',
    rules: [
      'Complete 8,000 steps daily',
      'Must complete all 3 days',
      'Equal split',
    ],
    createdAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const mockParticipants: ChallengeParticipant[] = [
  {
    id: 'participant-1',
    challengeId: 'challenge-1',
    userId: DEFAULT_USER.id,
    userName: DEFAULT_USER.name,
    userAvatar: '👤',
    status: 'active',
    daysCompleted: 0,
    joinedAt: new Date().toISOString(),
  },
  {
    id: 'participant-2',
    challengeId: 'challenge-1',
    userId: 'user-john',
    userName: 'John D.',
    userAvatar: '👨',
    status: 'active',
    daysCompleted: 0,
    joinedAt: new Date(now.getTime() - 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'participant-3',
    challengeId: 'challenge-1',
    userId: 'user-jane',
    userName: 'Jane S.',
    userAvatar: '👩',
    status: 'active',
    daysCompleted: 0,
    joinedAt: new Date(now.getTime() - 2 * 60 * 60 * 1000).toISOString(),
  },
];

export const mockDailyCheckins: DailyCheckin[] = [
  {
    id: 'checkin-1',
    challengeId: 'challenge-5',
    userId: DEFAULT_USER.id,
    date: new Date(now.getTime() - 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    steps: 9250,
    targetMet: true,
    checkinAt: new Date(now.getTime() - 20 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'checkin-2',
    challengeId: 'challenge-5',
    userId: DEFAULT_USER.id,
    date: new Date().toISOString().split('T')[0],
    steps: 6800,
    targetMet: false,
    checkinAt: new Date().toISOString(),
  },
];
